"""empty message

Revision ID: 069da73971a4
Revises: 
Create Date: 2024-07-24 11:45:24.882618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '069da73971a4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('idProfile', sa.Integer(), nullable=True))
        batch_op.alter_column('profile',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.create_foreign_key(None, 'profile', ['idProfile'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('profile',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.drop_column('idProfile')

    op.drop_table('profile')
    # ### end Alembic commands ###
