"""empty message

Revision ID: 105ef253294c
Revises: 1876c730a9ba
Create Date: 2024-08-04 20:13:48.802915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '105ef253294c'
down_revision = '1876c730a9ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Brand', sa.String(length=100), nullable=False))
        batch_op.create_unique_constraint(None, ['prodname'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('Brand')

    # ### end Alembic commands ###
