"""empty message

Revision ID: 1160c70eba33
Revises: 673cbeae45e3
Create Date: 2024-08-23 16:53:13.311404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1160c70eba33'
down_revision = '673cbeae45e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('productentry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('cost_price', sa.Integer(), nullable=False),
    sa.Column('amount_Prev', sa.Integer(), nullable=False),
    sa.Column('salesPrice_prev', sa.Integer(), nullable=False),
    sa.Column('id_prod', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_prod'], ['products.id_prod'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('productentry')
    # ### end Alembic commands ###
