"""empty message

Revision ID: 1876c730a9ba
Revises: 89476629435b
Create Date: 2024-08-04 20:02:38.296189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1876c730a9ba'
down_revision = '89476629435b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categoryproduct', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['category'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categoryproduct', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
