"""empty message

Revision ID: 21775e210838
Revises: 6d8a98531e95
Create Date: 2024-08-21 19:48:24.614875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21775e210838'
down_revision = '6d8a98531e95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('nit', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=60), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('idUser', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idUser'], ['user.id'], ),
    sa.PrimaryKeyConstraint('nit')
    )
    op.create_table('productentry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_prod', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('cost_price', sa.Integer(), nullable=False),
    sa.Column('idProd', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idProd'], ['products.id_prod'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('address',
    sa.Column('nit', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=60), nullable=False),
    sa.Column('city', sa.String(length=60), nullable=False),
    sa.Column('country', sa.String(length=60), nullable=False),
    sa.ForeignKeyConstraint(['nit'], ['customer.nit'], ),
    sa.PrimaryKeyConstraint('nit')
    )
    op.create_table('sales',
    sa.Column('idSales', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('totalPrice', sa.Integer(), nullable=False),
    sa.Column('iduser', sa.Integer(), nullable=True),
    sa.Column('nit', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['iduser'], ['user.id'], ),
    sa.ForeignKeyConstraint(['nit'], ['customer.nit'], ),
    sa.PrimaryKeyConstraint('idSales')
    )
    with op.batch_alter_table('detailsales', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'sales', ['idSales'], ['idSales'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detailsales', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    op.drop_table('sales')
    op.drop_table('address')
    op.drop_table('productentry')
    op.drop_table('customer')
    # ### end Alembic commands ###
