"""empty message

Revision ID: 3121f39b7924
Revises: 773023b0bf29
Create Date: 2024-08-21 19:34:52.015142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3121f39b7924'
down_revision = '773023b0bf29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('productentry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_prod', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('cost_price', sa.Integer(), nullable=False),
    sa.Column('idProd', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idProd'], ['products.id_prod'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.DateTime(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=15),
               nullable=False)

    op.drop_table('productentry')
    # ### end Alembic commands ###
