"""Aumentar longitud de la columna password a 255 caracteres

Revision ID: 4fba9dd47cc7
Revises: 3dcc59ff6762
Create Date: 2024-08-20 13:44:44.275325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fba9dd47cc7'
down_revision = '3dcc59ff6762'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_approved')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_approved', sa.BOOLEAN(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
