"""empty message

Revision ID: 50ac9106a150
Revises: ee8afe74b258
Create Date: 2024-08-21 20:20:01.909696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50ac9106a150'
down_revision = 'ee8afe74b258'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productentry', schema=None) as batch_op:
        batch_op.alter_column('id_prod',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint('productentry_idProd_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'products', ['id_prod'], ['id_prod'])
        batch_op.drop_column('idProd')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productentry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('idProd', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('productentry_idProd_fkey', 'products', ['idProd'], ['id_prod'])
        batch_op.alter_column('id_prod',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
