"""empty message

Revision ID: 50f84679e8ef
Revises: 91ed56498846
Create Date: 2024-07-30 14:58:23.629666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50f84679e8ef'
down_revision = '91ed56498846'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nit', sa.Integer(), nullable=False))
        batch_op.drop_column('id')

    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('customer_idAddr_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'address', ['id'], ['nit'])
        batch_op.drop_column('idAddr')

    with op.batch_alter_table('provider', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('provider_idAddr_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'address', ['id'], ['nit'])
        batch_op.drop_column('idAddr')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('provider', schema=None) as batch_op:
        batch_op.add_column(sa.Column('idAddr', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('provider_idAddr_fkey', 'address', ['idAddr'], ['id'])
        batch_op.drop_column('id')

    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('idAddr', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('customer_idAddr_fkey', 'address', ['idAddr'], ['id'])
        batch_op.drop_column('id')

    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('address_id_seq'::regclass)"), autoincrement=True, nullable=False))
        batch_op.drop_column('nit')

    # ### end Alembic commands ###
