"""empty message

Revision ID: 673cbeae45e3
Revises: 70ed31a43a6e
Create Date: 2024-08-23 16:51:06.899948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '673cbeae45e3'
down_revision = '70ed31a43a6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productentry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount_Prev', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('salesPrice_prev', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productentry', schema=None) as batch_op:
        batch_op.drop_column('salesPrice_prev')
        batch_op.drop_column('amount_Prev')

    # ### end Alembic commands ###
