"""empty message

Revision ID: 6cbb4a2c6e79
Revises: 1e3d9ae197f1
Create Date: 2024-07-24 02:12:38.612804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cbb4a2c6e79'
down_revision = '1e3d9ae197f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('profile',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('profile',
               existing_type=sa.String(length=20),
               type_=sa.BOOLEAN(),
               existing_nullable=False)

    # ### end Alembic commands ###
