"""empty message

Revision ID: 7216a45faaa7
Revises: f433d48fbed2
Create Date: 2024-08-02 13:25:02.333233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7216a45faaa7'
down_revision = 'f433d48fbed2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'provider', ['nit'], ['nit'])

    with op.batch_alter_table('provider', schema=None) as batch_op:
        batch_op.drop_constraint('provider_id_fkey', type_='foreignkey')
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('provider', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('provider_id_fkey', 'address', ['id'], ['nit'])

    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
