"""empty message

Revision ID: 7689d3804830
Revises: 7f9adba1782e
Create Date: 2024-08-05 20:10:38.826059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7689d3804830'
down_revision = '7f9adba1782e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales',
    sa.Column('idSales', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('totalPrice', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('nit', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['nit'], ['customer.nit'], ),
    sa.PrimaryKeyConstraint('idSales')
    )
    op.create_table('detailsales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('unitPrice', sa.Integer(), nullable=False),
    sa.Column('idSales', sa.Integer(), nullable=True),
    sa.Column('id_prod', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idSales'], ['sales.idSales'], ),
    sa.ForeignKeyConstraint(['id_prod'], ['products.id_prod'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detailsales')
    op.drop_table('sales')
    # ### end Alembic commands ###
