"""empty message

Revision ID: 89476629435b
Revises: ce19d34a0aba
Create Date: 2024-08-04 15:17:29.603208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89476629435b'
down_revision = 'ce19d34a0aba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categoryproduct', schema=None) as batch_op:
        batch_op.add_column(sa.Column('marca', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categoryproduct', schema=None) as batch_op:
        batch_op.drop_column('marca')

    # ### end Alembic commands ###
