"""empty message

Revision ID: 9c16de60890c
Revises: f2784c38cd34
Create Date: 2024-08-23 22:07:35.777612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c16de60890c'
down_revision = 'f2784c38cd34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id_prod', sa.Integer(), nullable=False),
    sa.Column('prodname', sa.String(length=60), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=False),
    sa.Column('salesPrice', sa.Integer(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('idCatProd', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idCatProd'], ['categoryproduct.idCatProd'], ),
    sa.PrimaryKeyConstraint('id_prod'),
    sa.UniqueConstraint('prodname')
    )
    op.create_table('customer',
    sa.Column('nit', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=60), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('idUser', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idUser'], ['user.id'], ),
    sa.PrimaryKeyConstraint('nit')
    )
    op.create_table('productentry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('cost_price', sa.Integer(), nullable=False),
    sa.Column('amount_Prev', sa.Integer(), nullable=False),
    sa.Column('salesPrice_prev', sa.Integer(), nullable=False),
    sa.Column('id_prod', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_prod'], ['products.id_prod'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('address',
    sa.Column('nit', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=60), nullable=False),
    sa.Column('city', sa.String(length=60), nullable=False),
    sa.Column('country', sa.String(length=60), nullable=False),
    sa.ForeignKeyConstraint(['nit'], ['customer.nit'], ),
    sa.PrimaryKeyConstraint('nit')
    )
    op.create_table('sales',
    sa.Column('idSales', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('totalPrice', sa.Integer(), nullable=False),
    sa.Column('iduser', sa.Integer(), nullable=True),
    sa.Column('nit', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['iduser'], ['user.id'], ),
    sa.ForeignKeyConstraint(['nit'], ['customer.nit'], ),
    sa.PrimaryKeyConstraint('idSales')
    )
    op.create_table('detailsales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('unitPrice', sa.Integer(), nullable=False),
    sa.Column('idSales', sa.Integer(), nullable=True),
    sa.Column('id_prod', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idSales'], ['sales.idSales'], ),
    sa.ForeignKeyConstraint(['id_prod'], ['products.id_prod'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detailsales')
    op.drop_table('sales')
    op.drop_table('address')
    op.drop_table('productentry')
    op.drop_table('customer')
    op.drop_table('products')
    # ### end Alembic commands ###
