"""empty message

Revision ID: ace6d55d8433
Revises: ae2958d1d4a5
Create Date: 2024-08-04 20:26:12.138909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ace6d55d8433'
down_revision = 'ae2958d1d4a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoryproduct',
    sa.Column('idCatProd', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('idCatProd'),
    sa.UniqueConstraint('category')
    )
    op.create_table('products',
    sa.Column('id_prod', sa.Integer(), nullable=False),
    sa.Column('prodname', sa.String(length=60), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=False),
    sa.Column('salesPrice', sa.Integer(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('idCatProd', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idCatProd'], ['categoryproduct.idCatProd'], ),
    sa.PrimaryKeyConstraint('id_prod'),
    sa.UniqueConstraint('prodname')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    op.drop_table('categoryproduct')
    # ### end Alembic commands ###
