"""empty message

Revision ID: ae2958d1d4a5
Revises: b428bf6eaa0d
Create Date: 2024-08-04 20:21:29.188210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae2958d1d4a5'
down_revision = 'b428bf6eaa0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categoryproduct', schema=None) as batch_op:
        batch_op.drop_column('marca')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categoryproduct', schema=None) as batch_op:
        batch_op.add_column(sa.Column('marca', sa.VARCHAR(length=100), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
