"""empty message

Revision ID: b428bf6eaa0d
Revises: 105ef253294c
Create Date: 2024-08-04 20:14:56.069389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b428bf6eaa0d'
down_revision = '105ef253294c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brand', sa.String(length=100), nullable=False))
        batch_op.drop_column('Brand')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Brand', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_column('brand')

    # ### end Alembic commands ###
