"""empty message

Revision ID: dcbb8d5e36a9
Revises: b9d5baef7935
Create Date: 2024-07-30 17:15:44.453539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcbb8d5e36a9'
down_revision = 'b9d5baef7935'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.add_column(sa.Column('costumer', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'customer', ['costumer'], ['nit'])

    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_constraint('customer_addrNit_fkey', type_='foreignkey')
        batch_op.drop_column('addrNit')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('addrNit', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('customer_addrNit_fkey', 'address', ['addrNit'], ['nit'])

    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('costumer')

    # ### end Alembic commands ###
