"""empty message

Revision ID: efb80f37400e
Revises: 289b8cf4db00
Create Date: 2024-07-30 19:22:16.265150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efb80f37400e'
down_revision = '289b8cf4db00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_nit', sa.Integer(), nullable=True))
        batch_op.drop_constraint('address_customer_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'customer', ['customer_nit'], ['nit'], ondelete='CASCADE')
        batch_op.drop_column('customer')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('address_customer_fkey', 'customer', ['customer'], ['nit'])
        batch_op.drop_column('customer_nit')

    # ### end Alembic commands ###
