"""empty message

Revision ID: f433d48fbed2
Revises: a23e2e3b8ade
Create Date: 2024-07-30 19:46:12.013350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f433d48fbed2'
down_revision = 'a23e2e3b8ade'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.drop_constraint('address_customer_nit_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'customer', ['nit'], ['nit'])
        batch_op.drop_column('customer_nit')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_nit', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('address_customer_nit_fkey', 'customer', ['customer_nit'], ['nit'], ondelete='CASCADE')

    # ### end Alembic commands ###
